version: '2'
services:

  # The Application
  app:
    build:
      context: ./.docker
      dockerfile: app.dockerfile
      args:
        - uid=${USER_ID}
        - user=laravel
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    # user: ${USER_ID:-1000}:${GROUP_ID:-1000}

  # The Web Server
  web:
    build:
      context: ./.docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "a@yaoishd8yhas"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
